import {
  OmdbSearchData,
  OmdbSearchQuery,
} from '../../../../../../../interfaces';

export const mockSearchResponse = [
  {
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    year: '2001',
    imdbId: 'tt0120737',
    type: 'movie',
  },
  {
    title: 'The Lord of the Rings: The Return of the King',
    year: '2003',
    imdbId: 'tt0167260',
    type: 'movie',
  },
  {
    title: 'The Lord of the Rings: The Two Towers',
    year: '2002',
    imdbId: 'tt0167261',
    type: 'movie',
  },
  {
    title: 'The Lord of the Rings',
    year: '1978',
    imdbId: 'tt0077869',
    type: 'movie',
  },
  {
    title: 'The Lord of the Rings: The Two Towers',
    year: '2002',
    imdbId: 'tt0347436',
    type: 'game',
  },
  {
    title: 'The Lord of the Rings: The Return of the King',
    year: '2003',
    imdbId: 'tt0387360',
    type: 'game',
  },
  {
    title: 'The Lord of the Rings: The Battle for Middle-Earth II',
    year: '2006',
    imdbId: 'tt0760172',
    type: 'game',
  },
  {
    title: 'The Lord of the Rings: The Battle for Middle-Earth',
    year: '2004',
    imdbId: 'tt0412935',
    type: 'game',
  },
  {
    title:
      'The Lord of the Rings: The Battle for Middle-earth II - The Rise of the Witch-king',
    year: '2006',
    imdbId: 'tt1058040',
    type: 'game',
  },
  {
    title: 'The Lord of the Rings: The Third Age',
    year: '2004',
    imdbId: 'tt0415947',
    type: 'game',
  },

  {
    title: 'The Dark Knight',
    year: '2008',
    imdbId: 'tt0468569',
    type: 'movie',
  },
  {
    title: 'The Dark Knight Rises',
    year: '2012',
    imdbId: 'tt1345836',
    type: 'movie',
  },
  {
    title: 'Thor: The Dark World',
    year: '2013',
    imdbId: 'tt1981115',
    type: 'movie',
  },
  {
    title: 'Transformers: Dark of the Moon',
    year: '2011',
    imdbId: 'tt1399103',
    type: 'movie',
  },
  {
    title: 'Zero Dark Thirty',
    year: '2012',
    imdbId: 'tt1790885',
    type: 'movie',
  },
  {
    title: 'Dark',
    year: '2017–2020',
    imdbId: 'tt5753856',
    type: 'series',
  },
  {
    title: 'Dark Shadows',
    year: '2012',
    imdbId: 'tt1077368',
    type: 'movie',
  },
  {
    title: 'Dark City',
    year: '1998',
    imdbId: 'tt0118929',
    type: 'movie',
  },
  {
    title: 'X-Men: Dark Phoenix',
    year: '2019',
    imdbId: 'tt6565702',
    type: 'movie',
  },
  {
    title: 'Terminator: Dark Fate',
    year: '2019',
    imdbId: 'tt6450804',
    type: 'movie',
  },
  {
    title: 'Crazy, Stupid, Love',
    year: '2011',
    imdbId: 'tt1570728',
    type: 'movie',
  },
  {
    title:
      'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
    year: '1964',
    imdbId: 'tt0057012',
    type: 'movie',
  },
  {
    title: 'Love Actually',
    year: '2003',
    imdbId: 'tt0314331',
    type: 'movie',
  },
  {
    title: 'Shakespeare in Love',
    year: '1998',
    imdbId: 'tt0138097',
    type: 'movie',
  },
  {
    title: 'P.S. I Love You',
    year: '2007',
    imdbId: 'tt0431308',
    type: 'movie',
  },
  {
    title: 'I Love You, Man',
    year: '2009',
    imdbId: 'tt1155056',
    type: 'movie',
  },
  {
    title: 'Love & Other Drugs',
    year: '2010',
    imdbId: 'tt0758752',
    type: 'movie',
  },
  {
    title: 'Punch-Drunk Love',
    year: '2002',
    imdbId: 'tt0272338',
    type: 'movie',
  },
  {
    title: 'In the Mood for Love',
    year: '2000',
    imdbId: 'tt0118694',
    type: 'movie',
  },
  {
    title: 'Love, Rosie',
    year: '2014',
    imdbId: 'tt1638002',
    type: 'movie',
  },
  {
    title: 'Death Proof',
    year: '2007',
    imdbId: 'tt1028528',
    type: 'movie',
  },
  {
    title: 'Death Note',
    year: '2006–2007',
    imdbId: 'tt0877057',
    type: 'series',
  },
  {
    title: 'Death Race',
    year: '2008',
    imdbId: 'tt0452608',
    type: 'movie',
  },
  {
    title: 'Happy Death Day',
    year: '2017',
    imdbId: 'tt5308322',
    type: 'movie',
  },
  {
    title: 'Death at a Funeral',
    year: '2007',
    imdbId: 'tt0795368',
    type: 'movie',
  },
  {
    title: 'Maze Runner: The Death Cure',
    year: '2018',
    imdbId: 'tt4500922',
    type: 'movie',
  },
  {
    title: 'Death Becomes Her',
    year: '1992',
    imdbId: 'tt0104070',
    type: 'movie',
  },
  {
    title: 'Love, Death & Robots',
    year: '2019–',
    imdbId: 'tt9561862',
    type: 'series',
  },
  {
    title: 'The Death of Stalin',
    year: '2017',
    imdbId: 'tt4686844',
    type: 'movie',
  },
  {
    title: 'Death Note',
    year: '2017',
    imdbId: 'tt1241317',
    type: 'movie',
  },
  {
    title: 'The Skin I Live In',
    year: '2011',
    imdbId: 'tt1189073',
    type: 'movie',
  },
  {
    title: 'Under the Skin',
    year: '2013',
    imdbId: 'tt1441395',
    type: 'movie',
  },
  {
    title: 'Mysterious Skin',
    year: '2004',
    imdbId: 'tt0370986',
    type: 'movie',
  },
  {
    title: 'Cold Skin',
    year: '2017',
    imdbId: 'tt1034385',
    type: 'movie',
  },
  {
    title: 'Skin',
    year: '2018',
    imdbId: 'tt6043142',
    type: 'movie',
  },
  {
    title: 'Skin Trade',
    year: '2014',
    imdbId: 'tt1641841',
    type: 'movie',
  },
  {
    title: 'The Reflecting Skin',
    year: '1990',
    imdbId: 'tt0100469',
    type: 'movie',
  },
  {
    title: 'On My Skin: The Last Seven Days of Stefano Cucchi',
    year: '2018',
    imdbId: 'tt7121252',
    type: 'movie',
  },
  {
    title: 'The Soft Skin',
    year: '1964',
    imdbId: 'tt0058458',
    type: 'movie',
  },
  {
    title: 'In Their Skin',
    year: '2012',
    imdbId: 'tt1790869',
    type: 'movie',
  },
  {
    title: 'In the Heart of the Sea',
    year: '2015',
    imdbId: 'tt1390411',
    type: 'movie',
  },
  {
    title: 'Crazy Heart',
    year: '2009',
    imdbId: 'tt1263670',
    type: 'movie',
  },
  {
    title: 'Wild at Heart',
    year: '1990',
    imdbId: 'tt0100935',
    type: 'movie',
  },
  {
    title: 'Angel Heart',
    year: '1987',
    imdbId: 'tt0092563',
    type: 'movie',
  },
  {
    title: 'I Heart Huckabees',
    year: '2004',
    imdbId: 'tt0356721',
    type: 'movie',
  },
  {
    title: 'Whisper of the Heart',
    year: '1995',
    imdbId: 'tt0113824',
    type: 'movie',
  },
  {
    title: 'The Normal Heart',
    year: '2014',
    imdbId: 'tt1684226',
    type: 'movie',
  },
  {
    title: 'Where the Heart Is',
    year: '2000',
    imdbId: 'tt0198021',
    type: 'movie',
  },
  {
    title: 'A Mighty Heart',
    year: '2007',
    imdbId: 'tt0829459',
    type: 'movie',
  },
  {
    title: 'The Beat That My Heart Skipped',
    year: '2005',
    imdbId: 'tt0411270',
    type: 'movie',
  },
];

export const mockSearchQuery: OmdbSearchQuery = {
  s: 'Lord of the rings',
};
